export enum CARD_TYPE {
  PRIMARY_INDUSTRY,
  SECONDARY_INDUSTRY,
  MAJOR_ESTABLISHMENT,
  LANDMARK,
  RESTAURANT,
}

export const CARD_ACTIVATION_ORDER = [
  CARD_TYPE.RESTAURANT,
  CARD_TYPE.PRIMARY_INDUSTRY,
  CARD_TYPE.SECONDARY_INDUSTRY,
  CARD_TYPE.MAJOR_ESTABLISHMENT,
];

export enum CARD_TAG {
  WHEAT,
  SUITCASE,
  MAJOR,
  GEAR,
  FRUIT,
  FACTORY,
  CUP,
  COW,
  BREAD,
  BOAT,
}
